# Generated by Django 3.2.7 on 2021-09-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroapi', '0002_auto_20210915_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='heroapi.creator'),
        ),
    ]
