# Generated by Django 3.2.7 on 2021-09-23 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroapi', '0003_alter_hero_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroapi.creator'),
        ),
    ]
